#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

runApplication blockMesh
runApplication topoSet
runApplication subsetMesh -overwrite c0 -patch floatingObject
cp -r 0.org 0 > /dev/null 2>&1
runApplication setFields
#runApplication $application

runApplication decomposePar

#for proc in processor*
#do
 #  cp -r 0.org $proc/0 > /dev/null 2>&1
#done

#runParallel setFields 4
runParallel $application 4

runApplication reconstructPar
