#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

runApplication blockMesh

runApplication -s 1 topoSet -dict system/topoSetDict1
runApplication -s 1 subsetMesh -overwrite c0 -patch floatingObject1

runApplication -s 2 topoSet -dict system/topoSetDict2
runApplication -s 2 subsetMesh -overwrite c1 -patch floatingObject2

runApplication -s 3 topoSet -dict system/topoSetDict3
runApplication -s 3 subsetMesh -overwrite c2 -patch floatingObject3

runApplication -s 4 topoSet -dict system/topoSetDict4
runApplication -s 4 subsetMesh -overwrite c3 -patch floatingObject4

runApplication -s 5 topoSet -dict system/topoSetDict5
runApplication -s 5 subsetMesh -overwrite c4 -patch floatingObject5

runApplication -s selectBottom1 \
    topoSet -dict system/topoSetDict-selectBottom1

runApplication -s selectBottom2 \
    topoSet -dict system/topoSetDict-selectBottom2

runApplication -s selectBottom3 \
    topoSet -dict system/topoSetDict-selectBottom3

runApplication -s selectBottom4 \
    topoSet -dict system/topoSetDict-selectBottom4

runApplication -s selectBottom5 \
    topoSet -dict system/topoSetDict-selectBottom5

runApplication -s 1 createPatch -dict system/createPatchDict


rm -r ./constant/polyMesh
mv ./0.001/polyMesh ./constant/
rm -r ./0.001/

cp -r 0.orig 0 > /dev/null 2>&1

runApplication setFields

runApplication decomposePar
runParallel $application
runApplication reconstructPar

#------------------------------------------------------------------------------
